### ISSUE TITLE
add crits to weapon

### ISSUE THREAD

**Issue by Eoksni** [emotz/kladovka#10]
- Crit chance
- Crit damage

**Comment by Eoksni** [comment]
1 + critchance*critdamage

**Comment by Eoksni** [comment]
например если 20% крита с +100% крит дамагом, то итоговый дамаг увеличится от критов на 20%

**Comment by Eoksni** [comment]
если 40% крита с +150% крит дамаги, то итоговый дамаг увеличится от критов на 60%

**Comment by ITarako** [comment]
крит присутсвует по желанию или маст хев?

**Comment by Eoksni** [comment]
по желанию

**Comment by ITarako** [comment]
мб ошибку`mustBePositive` переделать в `mustNotBeNegative`
0 крита, вполне легальное отсутствие крита
0 дмг.. палка х)

**Comment by ITarako** [comment]
имел ввиду что палка с миндмг 0 и махдмг 1 выглядит легально. ну да ладно, пусть будет еще проверка
хм..и как лучше назвать ф-цию для нахождения отрицательный чисел, чтобы была консистента с `filterNotPositive`, `filterNotNumbers`

**Comment by Eoksni** [comment]
нет, палка с миндмг 0 и махдмг 1 выглядит не очень легально если честно.

`filterNegative` ?

**Comment by Eoksni** [comment]
потому что у нас легальным является махдмг равный миндмг, верно? а палка с 0-0 дамагом слегка ущербна

**Comment by Eoksni** [comment]
кстати statControl во фронте это не отражает. даже в таком простом случае появился рассинхрон валидаций. поэтому, по хорошему, все валидации надо как-то централизировать.

**Comment by ITarako** [comment]
как раз фиксил statControl, чтобы мин и мах могли быть равными х)
похоже намечается исус "Validation come back"

**Comment by ITarako** [comment]
[closed #10](https://github.com/emotz/kladovka/pull/69/commits/2d25b8f78baf57dfc9620066946eeedb30db1026)
