### ISSUE TITLE
travis cashe

### ISSUE THREAD

**Issue by ITarako** [emotz/kladovka#111]

**Comment by Eoksni** [comment]
see https://github.com/emotz/kladovka/issues/101
after that, just add
```
cache:
  directories:
    - yarn-cache
```

**Comment by Eoksni** [comment]
you also need to specify yarn cache directory for part of the build that run outside of docker
you can do that using --cache-folder yarn flag

**Comment by Eoksni** [comment]
dont cache node_modules, yarn cache dir is enough
