### ISSUE TITLE
move .eslintignore to frontend?

### ISSUE THREAD

**Issue by Eoksni** [emotz/kladovka#38]
Should we have root .eslintignore with all ignore dirs and files, or every sub-project (sub-directory) should have its own ignores?

**Comment by ITarako** [comment]
к `.eslintignore` отношусь как `.gitignore` . один на весь проект и даже синтаксис одинаков, так-что предпочел бы оставить его в корне
подпроекты итак зависят от корня, например тот же конфиг ellint'а, так что имхо пусть будут более зависимы чем плодить файлы в поддиректориях

**Comment by Eoksni** [comment]
👍
