### ISSUE TITLE
calculate effectiveness of "broken promises"

### ISSUE THREAD

**Issue by Eoksni** [emotz/kladovka#39]
https://us.battle.net/d3/en/item/broken-promises
After 5 consecutive non-critical hits, your chance to critically hit is increased to 100% for 3 seconds.

given the crit chance, crit damage and number of hits per second, what is the average dps increase from this effect?

**Comment by Eoksni** [comment]
Write function:
```js
/** @returns {Number} average dps increase (percent) */
function dpsIncreaseWithBrokenPromises(critChance, critDmg, hitsPerSeconds) {...}
```

**Comment by ITarako** [comment]
ну нахрен, пусть еноты это решают

**Comment by Eoksni** [comment]
wut? какие еноты?

**Comment by ITarako** [comment]
хз как это решать

**Comment by Eoksni** [comment]
что у тебя было по терверу ? :)
ладно давай забьем тогда, это все-таки к программированию только косвенно относится, лучше на других задачах сконцентрируемся.
