### ISSUE TITLE
put all logs into logs

### ISSUE THREAD

**Issue by Eoksni** [emotz/kladovka#42]
Make root dir `logs` and put there `errorShots` from webdriver and all future logs (ie vagrant logs if we will use it or logs from dev server).

**Comment by Eoksni** [comment]
закрываешь исусы без линка к коммиту, атата

**Comment by ITarako** [comment]
[closed #42](https://github.com/emotz/kladovka/pull/49/commits/93bad75eabe32f74ab383b2ce3609d2b0a6b2906)
