### ISSUE TITLE
add character

### ISSUE THREAD

**Issue by Eoksni** [emotz/kladovka#66]
In the middle of the page, there should be form to enter following stats:

- +crit damage
- +crit chance
- +attack speed
- +dmg (e.g. +50 dmg)

There should be button "update".
When we click "update", dps of each item should be recalculated.

**Comment by ITarako** [comment]
[close](https://github.com/emotz/kladovka/pull/75/commits/07aa4c0f9bdb08458a7080d77e1e54ac8e347058)
